apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kinspire-public
  namespace: auth-system
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kinspire-public
  namespace: auth-system
subjects: # All serviceaccounts
- kind: Group
  name: system:serviceaccounts
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: kinspire-public
  apiGroup: rbac.authorization.k8s.io