apiVersion: v1
kind: Service
metadata:
  name: gitea
spec:
  ports:
    - name: https
      port: 443
      targetPort: 8443
  selector:
    app: gitea
  type: ClusterIP
---

apiVersion: v1
kind: Service
metadata:
  name: gitea-ssh
spec:
  ports:
    - name: ssh
      port: 22
      protocol: TCP
      targetPort: ssh
  selector:
    app: gitea
  type: ClusterIP