apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitea
spec:
  podManagementPolicy: Parallel
  serviceName: gitea
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      serviceAccount: gitea
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      terminationGracePeriodSeconds: 30
      containers:
      - name: gitea
        image: justinsb/gitea:latest
        ports:
        - containerPort: 8443
          protocol: TCP
          name: https
        volumeMounts:
        - name: data
          mountPath: /volumes/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
